config/routes.rb
Myorg::Application.routes.draw do

  root :to => 'employees#index'

  resources :roles  

  resources :departments
  
  resources :employees do
    get :autocomplete_employee_name, :on => :collection
  end
  

  get "addresses/show_map"
  
  match '/org_chart' => 'employees#org_chart', :as => :org_chart
  
  

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  role                :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  email               :string(255)
#  bio                 :text
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  reportsto           :string(255)
#  department_id       :integer
#  joined_on           :date
#  dob                 :date
#  personal_email      :string(255)
#  manager_id          :integer
#  sex                 :string(255)
#

class Employee < ActiveRecord::Base
 
  
  include Gravtastic
  gravtastic  :default => "http://cdn1.iconfinder.com/data/icons/dragon/128/User.png",
              :size => 120
              
            # http://cdn1.iconfinder.com/data/icons/dragon/128/User.png  
            #  http://s3.amazonaws.com/twitvid-channel-avatars/4f8daf56e6438.1.jpg  
            #  http://www.techinasia.com/techinasia/wp-content/uploads/2009/11/facebook-avatar.png
   
  attr_accessible :name, :sex, :role, :role_ids, :email, :personal_email, :bio, :avatar, :employee_ids, :address, :department_id, :dob, :joined_on, :address_attributes, :phones_attributes, :manager_id
  
  validates :name, 
            :presence => true, 
            :format => { :with => /^[^0-9`!@#\$%\^&*+_=]+$/,
                         :message => "Only letters allowed" 
                       }
  
    validates :email,   
              :presence => true,   
              :uniqueness => true,   
              :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }  
  
  
  # validates :personal_email,   
  #           :uniqueness => true,   
  #           :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }              
                                             
  has_and_belongs_to_many :roles
  has_many :subordinates, class_name: "Employee",
                            foreign_key: "manager_id"
 
  belongs_to :manager, class_name: "Employee"
 
 # has_and_belongs_to_many :employees, 
  #                        :join_table => "employees_connections",
   #                       :foreign_key => "employee_a_id",
    #                      :association_foreign_key => "employee_b_id"

  belongs_to :department
  has_one :address,  :dependent => :destroy
  has_many :phones, :dependent => :destroy
  accepts_nested_attributes_for :address, :reject_if => lambda { |a| a[:street_name].blank? },  :allow_destroy => true
  accepts_nested_attributes_for :phones, :reject_if => lambda { |p| p[:phone_number].blank? }, :allow_destroy => true
  
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" , :stamp => "20x20>"}
  

  self.per_page = 25
  

  
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
  
  
 
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :sort_column, :sort_direction
  autocomplete :employee, :name
  
  # GET /employees
  # GET /employees.json
  def index
   @search = Employee.metasearch(params[:search])
   @employees = @search.order(sort_column + " " + sort_direction).paginate(:page => params[:page])
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end


  # GET /employees/1
  # GET /employees/1.json
  def show
     @search = Employee.metasearch(params[:search]) 
    @employee = Employee.find(params[:id]) 
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
   #   format.xml
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @search = Employee.metasearch(params[:search])
    @employee = Employee.new
    @employee.build_address
    @employee.phones.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @search = Employee.metasearch(params[:search])
    @employee = Employee.find(params[:id])
     if !@employee.address.nil? then
        @employee.address
      else
        @employee.build_address
    end    
    
     @employee.phones.build
  end

  # POST /employees
  # POST /employees.json
  def create
    @search = Employee.metasearch(params[:search])
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
         @employee.build_address
         @employee.phones.build
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: @employee.name.to_s + ' was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: @employee.name.to_s + 'was successfully removed.' }
      format.json { head :no_content }
    end
  end
  
  def org_chart
    data_table = GoogleVisualr::DataTable.new
      data_table.new_column('string', 'Name'   )
      data_table.new_column('string', 'Manager')
      data_table.new_column('string', 'ToolTip')
      @managers = Employee.find(:all)
      @managers.each do |m|
        data_table.add_rows( [[{:v => m.name, :f => m.name+'<div style="color:red; font-style:italic">'+get_roles_title(m)+'</div>'}, get_manager_info(m), m.name]])        
      end
 
      opts   = { :allowHtml => true }
      @chart = GoogleVisualr::Interactive::OrgChart.new(data_table, opts)
  end
  
  private
  
    def sort_column
      Employee.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
    def get_managers
       @managers = Employee.find(:all, :group => "manager_id")
    end
    
    def get_manager_info(employee)
     # @employee = Employee.find(params[:id])
       employee.manager.nil? ? "" : employee.manager.name
     
    end
  
    def get_roles_title(employee)
     employee.roles.empty? ? "no role" : employee.roles.map {|r| r.title.to_s.inspect}.join(",").gsub("\"", "")
  end
  
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def get_manager
	   @employee.employees.each do |m| 
     m.name  
   end
  end
  
  def dob_date
    @employee.dob.strftime("%m-%d-%Y") unless  @employee.dob.nil? 
  end
  
  def joined_on_date
    @employee.joined_on.strftime("%m-%d-%Y") unless  @employee.joined_on.nil?
  end
  
  def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY'],
        ['Other', 'other']
      ]
  end
end

app/views/employees/_address.html.erb
<% if @employee.address.nil? %>
		<% then %>
		<span class="label"><%= "address not provided" %></span>
		<% else %>
		<%= @employee.address.street_name %>
		<%= @employee.address.apt if !@employee.address.apt.empty?  %><br/>
		<%= @employee.address.city %>,
		<%= @employee.address.state %>
		<%= @employee.address.zip %><br/>
		<%= @employee.address.country %>
		<% end %>

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :bio, :input_html => { :rows => 5, :class => 'input-xxlarge' } %>
  <%= f.input :sex, collection: ["Male", "Female"] %>
  <%= f.input :dob, :as => :string, :label => "Date of birth", :input_html => { :class => 'span3' } %>
  <%= f.input :joined_on, :as => :string, :input_html => { :class => 'span3' } %>
  <%= f.association :department,  collection: Department.all(order: 'name') %>
  <%= f.association :roles, collection: Role.all(order: 'title') %>
  <%#= f.association :employees,  :label => "Reports to" %>
   <%= f.association :manager,  collection: Employee.where("id != ?", @employee.id).order("name"), :label => "Reports to" %>
  <%= f.input :email, :label => "Work Email", :placeholder => 'Use valid email address' %>
  <%= f.input :personal_email, :placeholder => 'Use valid email address' %>
  
  <div class="control-group">
	<div class="controls">
	<p class="text-error"><%= @employee.address.errors.first[1] unless @employee.address.errors.empty? %></p>
  </div>
  <label class="control-label" for="address">Address</label>
  <div class="controls">
  	<%= f.simple_fields_for :address do |a| %>
	<%= a.input_field :street_name, :placeholder => 'Street', style: "margin-bottom:3px" %>
	<%= a.input_field :apt, :placeholder => 'Apt/Suite', class: 'span2', style: "margin-bottom:3px" %><br/>
  	<%= a.input_field :city, :placeholder => 'City', style: "margin-bottom:3px" %><br/>
  	<%= a.input_field :state, :collection => us_states, :include_blank => false, :prompt => "Select state", class: 'span3', style: "margin-bottom:3px" %>	
  	<%= a.input_field :zip, class: 'span2', :placeholder => 'Zip/Pin code', style: "margin-bottom:3px"  %><br/>
	<%= a.input_field :country, class: 'span3', :selected => ["United States"], :priority => [ "United States" ],  style: "margin-bottom:3px"  %>
  	<% end %>
	
</div>
</div>

  <div class="control-group">
  <label class="control-label" for="phones">Phone</label>
  <div class="controls">
	<%= f.simple_fields_for :phones do |p|  %>
	<%= p.input_field :phone_type, :collection => ["Home","Office","Mobile"], :include_blank => false,  class: 'span2', style: "margin-bottom:3px"   %>
	<%= p.input_field :phone_number, class: 'span2', style: "margin-bottom:3px"  %><br/>
	<% end %> 
</div>
</div>

    <%= f.input :avatar %>
   
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), employees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/employees/_manager.html.erb
 <% if @employee.manager.nil? %>
	<span class="label label-info"> <%= "not assigned" %></span>
	 <% else %>
	<dd>	<%= link_to @employee.manager.name, employee_path(@employee.manager) %></dd>
	<% end %>

app/views/employees/_phones.html.erb
<% @phones = @employee.phones %>
    <% @phones.each do |p| %>
   <dd><%= p.phone_number %> <small>(<%= p.phone_type %>)</small></dd>
   <% end %>

app/views/employees/_roles.html.erb
<% if @employee.roles.empty? %>
	<span class="label label-info"> <%= "not assigned" %></span>
	<% else %>
<% @roles = @employee.roles %>
<% @roles.each do |role| %>
<dd><%= link_to role.title, role_path(role) %><br /></dd>
<% end %>
<% end %>
		
	   

app/views/employees/_search.html.erb
<form class="form-search"  align='right'>
		<%= form_for @search, :url => employees_path, :html => {:method => :get} do |f| %>
		<p>
			<%= f.text_field :name_or_role_or_department_name_contains %>
			<%= f.submit 'Search' , :class => 'btn btn-primary' %>
		</p>	
		<% end %>
	<!--  <input type="text" class="input-medium search-query">
	  <button type="submit" class="btn">Search</button> -->
	</form>

app/views/employees/_subordinates.html.erb
 <% if @employee.subordinates.empty? %>
<span class="label label-info"> <%= "no subordinates" %></span>
 <% else %>
 <% @employee.subordinates.each do |s| %>
<dd><%= link_to s.name, employee_path(s) %></dd>
<% end %>
<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h4><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human} info") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>

<div class="page-header" style="width: 100%; overflow: hidden;">
  <div id="title" style="width: 300px; float: left;"><h4><%=t '.title', :default => model_class.model_name.human.pluralize %></h4></div>
  <div :id="search" style="margin-left: 300px;"><%= render :partial => 'search' %></div>
 <span class="badge"> Total count:  <%= Employee.count %> </span>
</div>

<table class="table table-striped">
  <col width="1%" />
    <col width="10%" />
	<col width="20%" />
	<col width="20%" />
	<col width="20%" />
	<col width="20%" />
  <thead>
    <tr>
      <th><%= sortable 'id', 'Id' %></th>
	  <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= sortable 'name' %></th>
      <th><%= sortable 'department_id' %></th>
	  <th><%= sortable 'role' %></th>
	  <th><%= sortable 'reportsto', 'Reports to' %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.id %></td>
        <td><%= link_to (image_tag avatar_url_index_page(employee)), employee_path(employee) %></td>	
	<!--	<td><%= link_to (image_tag employee.gravatar_url), employee_path(employee) %></td>  -->

		<td><%= link_to employee.name, employee_path(employee) %> </td>
		
		<td> <dd><%= employee_department(employee) %></dd></td>
	<td>   
	    		<% @roles = employee.roles %>
	  			<% if @roles.empty? %>
				<span class="label label-info"><%= "not assigned" %></span>
				<% else %>
				<% @roles.each do |role| %>
	  		<dd><%= link_to role.title, role_path(role) %><br/></dd>
	  			<% end %>
				<% end %> 
		</td>
			<td>
		  	     <% if employee.manager.nil? %>
				<span class="label label-info"> <%= "not assigned" %></span>
				 <% else %>
		 	<dd>	<%= link_to employee.manager.name, employee_path(employee.manager) %></dd>
				<% end %>
			</td>
			
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
 <%= will_paginate @employees, :class => 'pagination' %>
 

<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-primary' %>
</div>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h4><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/employees/org_chart.html.erb
<div id='chart'></div>
<%= render_chart @chart, 'chart' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>

<div class="page-header">
	<h4><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "#{model_class.model_name.human} info") %></h4>
</div>

<table class="profile" summary="Profile information">
	  <col width="25%" />
  <tr>
    <td class="main" valign="top">
		<%= image_tag avatar_url_show_page(@employee), :class => 'img-polaroid' %>
		<!-- <%= image_tag @employee.gravatar_url %>
		<%= image_tag @employee.avatar.url %> -->
        <h4 align="left">
			<%= @employee.name %>
        </h4>
    </td>
    <td class="sidebar round">
	  <dl class="dl-horizontal">
	    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
	    <dd><%= @employee.name %></dd>
		<dl class="dl-horizontal">
  	  <dt><strong><%= model_class.human_attribute_name(:bio) %>:</strong></dt>
  	   <dd><%= @employee.bio %></dd>
   </dl>
   <dl class="dl-horizontal">
 	  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
    <dd><%= @employee.sex %></dd>
 </dl>
  <dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:date_of_birth) %>:</strong></dt>
   <dd><%= dob_date %></dd>
</dl>
  <dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:joined_on) %>:</strong></dt>
   <dd><%= joined_on_date %></dd>
</dl>
   
   <dl class="dl-horizontal">
   	  <dt><strong><%= model_class.human_attribute_name(:department) %>:</strong></dt>
   	   <dd><%= employee_department(@employee) %></dd>
   </dl>
	   <dl class="dl-horizontal">
	    <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
	    <dd>
	  	<%= render :partial => 'roles' %>

	  </dd>
  </dl>
	  <dl class="dl-horizontal">
		  <dt><strong><%= model_class.human_attribute_name(:work_email) %>:</strong></dt>
	   <dd><%= mail_to @employee.email %></dd>
   </dl>
  <dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:personal_email) %>:</strong></dt>
   <dd><%= mail_to @employee.personal_email %></dd>
</dl>
	   <dl class="dl-horizontal">
 	  <dt><strong><%= model_class.human_attribute_name(:reports_to) %>:</strong></dt>
	   <dd><%= render :partial => 'manager' %></dd>

	  </dl>
   <dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
	 <dd>
		 <%= render :partial => 'address' %>
	 </dd>	  
  </dl> 
  <dl class="dl-horizontal">
 <dt><strong><%= model_class.human_attribute_name(:phones) %>:</strong></dt>
 <%= render :partial => 'phones' %>
 </dl>
    
 <dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:subordinates) %>:</strong></dt>
 <dd>
	 <%= render :partial => 'subordinates' %>
 </dd>	  
</dl> 
  
	
	</td>
	
  </tr>
  
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>