config/routes.rb
Myorg::Application.routes.draw do

  root :to => 'employees#index'

  resources :roles  

  resources :departments
  
  resources :employees do
    get :autocomplete_employee_name, :on => :collection
  end
  

  get "addresses/show_map"
  
  match '/org_chart' => 'employees#org_chart', :as => :org_chart
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src='http://www.google.com/jsapi'></script>
    <title><%= content_for?(:title) ? yield(:title) : "MyOrg" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner"> 
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
		  <a><%= link_to "MyOrg", root_path, :class => 'brand' %></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Employees", employees_path  %></li>
              <li><%= link_to "Roles", roles_path  %></li>
			  <li><%= link_to "Departments", departments_path  %></li>
			  <li><%= link_to "Map View",  addresses_show_map_path  %></li>
              <li><%= link_to "Org Chart", org_chart_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">

      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Departments</li>
			  <% @departments = Department.all %>
			  <% @departments.each do |department| %>
			  <li><%= link_to department.name, department_path(department) %></li>
			  <% end %>
			  
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
		<div class="span9"> 
		  <%= bootstrap_flash %>
        <div class="navbar-inner">			 
		<div class="span12"> 

          <%= yield %>
		  
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<%= javascript_include_tag "application" %>
	 <%= javascript_include_tag "bootstrap-datepicker.js" %>
	<%= yield :scripts %>
  </body>
</html>